# Generated by Django 4.1 on 2023-07-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_data", "0002_rename_end_module_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="laboratory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistants",
                to="scheduling_data.laboratory",
            ),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistants",
                to="scheduling_data.semester",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="scheduling_data.module",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="scheduling_data.module",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="laboratory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratories",
                to="scheduling_data.laboratory",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratories",
                to="scheduling_data.semester",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="scheduling_data.semester",
            ),
        ),
    ]
